apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: microservices
build:
  artifacts:
    - image: order-service
      context: order-service
      docker:
        dockerfile: Dockerfile
    - image: payment-service
      context: payment-service
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/order-manifest.yml
    - k8s/payment-manifest.yml
